# Generated by Django 4.1.7 on 2023-03-17 16:56

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workouttracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='exercises',
        ),
        migrations.AlterField(
            model_name='workout',
            name='timeday',
            field=models.CharField(choices=[('MOR', 'Morning'), ('AFT', 'Afternoon'), ('EVE', 'Evening'), ('NIG', 'Night')], max_length=3),
        ),
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('CA', 'Cardio'), ('WA', 'Walking'), ('RU', 'Running'), ('HI', 'Hiking'), ('HT', 'Interval Training'), ('WT', 'Weights'), ('YO', 'Yoga'), ('HY', 'Hockey'), ('OC', 'Oculus'), ('OT', 'Other')], default=None, max_length=29, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
    ]
