# Generated by Django 4.1.7 on 2023-03-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouttracker', '0003_workout_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='current_weight',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
