# Generated by Django 4.1.7 on 2023-03-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouttracker', '0004_workout_current_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='cals_burned',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='current_weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
